### ISSUE TITLE
Allow to show all buffers in tabline even if multiple windows are open

### ISSUE THREAD

**Issue by jlebon** [pacha/vem-tabline#1]
Nice plugin! I'm still debating whether it's worth using this on top of Ctrl+P. I definitely like the fact that it only takes one line though, vs MiniBufExplorer.

One odd behaviour I noticed is:

- `vim file1.txt file2.txt`
- `:split`
- tabline says `file1.txt + 1 more` instead of listing `file2.txt` as well.

**Comment by jlebon** [comment]
OK reading the documentation more carefully now, it seems like this is by design.

```
For example, if you have 3 buffers: `buffer1`, `buffer2`, `buffer3` and the
tab has two windows showing the first 2 then you will see:
>
    | buffer1 | buffer2 | +1 more                                | 1 | 2 | 3 |
>
However, if there's only one window you'll see the three of them.
```

Any way we can force the behaviour of always showing all of them?

**Comment by pacha** [comment]
Yes @jlebon it is by design. But I think that it makes total sense to have such an option. I'll add it.

**Comment by pacha** [comment]
The option is already available. Add:
```
let g:vem_tabline_multiwindow_mode = 0
```
to your `vimrc` file to always show all buffers.
