### ISSUE TITLE
How to change border colour under tabline?

### ISSUE THREAD

**Issue by Jayphen** [pacha/vem-tabline#11]
Hello, thank you for this plugin, it's great!

This may not be specific to the plugin, but I'm wondering if you can tell me how I can change the border colour shown in the screenshot below? I am not sure whether colour is coming from the plugin, from vim, or from my terminal.

Thanks!

![CleanShot 2020-05-25 at 13 57 02](https://user-images.githubusercontent.com/329184/82810798-a4c35c80-9e8f-11ea-85f5-4daca77bf6d8.png)

**Comment by pacha** [comment]
Hi @Jayphen, sure :)

The underline comes from the color scheme file that you are using. Or from the default Vim configuration if you didn't set one specifically.
So the underline is a property of the text of the tab, not an attribute of the tabline. That means that you can't change the color of the underline and the color of the text independently. That is, the underline will always have the same color as the text.

You can, however, disable it. To do so you can add the following to your `.vimrc` file:
```
highlight Tabline cterm=none gui=none
highlight TablineSel cterm=none gui=none
```
In general, to change the colors of the tabline you use a configuration like this one:
```
highlight TabLine     term=reverse cterm=none ctermfg=0   ctermbg=251
highlight TabLineSel  term=bold    cterm=bold ctermfg=0   ctermbg=255
highlight TabLineFill term=reverse cterm=none ctermfg=246 ctermbg=251
```
`TabLine` is used for normal tabs, `TabLineSel` for the one selected and `TabLineFill` for the background color. For more info on what values you can put there you can check `:help :highlight`.

Hope it helps!

**Comment by wenijinew** [comment]
The below line will remove the underline:
`hi TabLine cterm=none`
