### ISSUE TITLE
[Bug] Modified flag is not displayed for an unsaved buffer

### ISSUE THREAD

**Issue by Dupond** [pacha/vem-tabline#16]
Hello,

If you simply open `vim` without any file and start to edit the empty buffer, the `[+]` modified flag is displayed in the status line (assuming it's configured to display it), but not in the Vem Tabline (no asterisk after "[No Name]"). However, `echo &modified` returns `1`, as it should.

If you save the file and then keep editing it, the flag is displayed.

Best regards,
Dupond

**Comment by pacha** [comment]
Hi Dupond,
True. Fixed in latest commit (a3c5b37e54e13248fb7503dbbad75b6ce7888c69).
Thanks for reporting!

**Comment by Dupond** [comment]
Thanx for the fix!
