### ISSUE TITLE
[feature request] Add DeleteCurrentBuffer to a <Plug> mapping

### ISSUE THREAD

**Issue by noib3** [pacha/vem-tabline#18]
Basically title. This would mean a cleaner `.vimrc` for everyone using this plugin, since instead of

```
nmap <silent> <Leader>x :call DeleteCurrentBuffer()<CR>

function! DeleteCurrentBuffer() abort
  let current_buffer = bufnr('%')
  let next_buffer = g:vem_tabline#tabline.get_replacement_buffer()
  try
    exec 'confirm ' . current_buffer . 'bdelete'
    if next_buffer != 0
      exec next_buffer . 'buffer'
    endif
  catch /E516:/
    " If the operation is cancelled, do nothing
  endtry
endfunction
```

one could simply have

```
nmap <Leader>x <Plug>vem_delete_buffer-
```

**Comment by pacha** [comment]
Hi @n0ibe,
That makes sense. I originally added the function to the README file so people could modify it if they wanted. But I see how having a mapping (along the lines of the existing ones) makes sense. I added the change to d27465a9c59f842d8635a93a38e4a26e7ce864d3. So it should be available now in master.
Please, let me know if it works fine for you.

**Comment by noib3** [comment]
@pacha Works great!
