### ISSUE TITLE
Only one buffer name visible when used in neovim with lightline

### ISSUE THREAD

**Issue by Again** [pacha/vem-tabline#2]
Ubuntu: 18.04
Neovim: v0.3.1-139-g2bfabd5bf (appimage)
Plugin manager: vim-plug

init.vim:
```
call plug#begin()
    Plug 'pacha/vem-tabline'
    Plug 'itchyny/lightline.vim'
call plug#end()
```

With lightline.vim enabled only one buffer name is displayed. If I remove lightline then vem-tabline works correctly.

**Comment by pacha** [comment]
It seems that lightline is taking over vem-tabline as it has some functionality to configure the tabline. If you want to use both together just disable that functionality in lightline with the option:
```
let g:lightline = {'enable': { 'tabline': 0}}
```

**Comment by Again** [comment]
Thanks, that fixed it.
