### ISSUE TITLE
[Feature request] command to go back to last used buffer

### ISSUE THREAD

**Issue by cowens** [pacha/vem-tabline#21]
A common use case for me is to have a bunch of files open, but to be mostly bouncing between two of them. It would be nice to be able to say

    let mapleader ,
    nmap <leader>, <Plug>vem_last_buffer-

And then type ,, to bounce between the most recent two files

**Comment by cowens** [comment]
Something like this, but more robust: [last_buffer.txt](https://github.com/pacha/vem-tabline/files/5223265/last_buffer.txt)

**Comment by pacha** [comment]
Hi @cowens,
What you describe sounds like the alternate file. You can do that natively in Vim with `Ctrl-^` (if that's difficult to type in your keyboard, you can also use `Ctrl-6`). Is that what you're looking for or did I misunderstand your explanation? :thinking:

**Comment by cowens** [comment]
Yep, that does exactly what I need, thanks.
