### ISSUE TITLE
Only current buffer shown in splits + next/previous nav not working

### ISSUE THREAD

**Issue by thet** [pacha/vem-tabline#3]
Thanks for this plugin! I was always missing reorderable buffer tabs since my swticht to vim.

I encountered two problems when working with splits:

- Only the current buffer in the split is show in the tabline
- The next/previous navigation does not work as expected - it selects another split window.

This is my key map for vem-tabline:
```
nmap <S-Left> :call vem_tabline#tabline.move_buffer('left')<CR>
nmap <S-Right> :call vem_tabline#tabline.move_buffer('right')<CR>
nmap <C-Left> :call vem_tabline#tabline.select_buffer('left')<CR>
nmap <C-Right> :call vem_tabline#tabline.select_buffer('right')<CR>
```

**Comment by pacha** [comment]
Hi @thet,
I think that what you're describing there is the multiwindow mode of the plugin. If you set the following variable in your `.vimrc`
```
let g:vem_tabline_multiwindow_mode = 0
```
all the buffers will appear in the tabline even if you have splits open and your key mappings will work as you expect.

**Comment by thet** [comment]
Thanks, you're right! Now it works as I want :)
