### ISSUE TITLE
<Plug> mappings not working

### ISSUE THREAD

**Issue by bokwoon95** [pacha/vem-tabline#4]
The documentation mentions

    For example you could set your mappings like:
    >
        nmap <leader>h <Plug>vem_tabline_move_buffer_left-
        nmap <leader>l <Plug>vem_tabline_move_buffer_right-
        nmap <leader>p <Plug>vem_tabline_prev_buffer-
        nmap <leader>n <Plug>vem_tabline_next_buffer-
    <

But the actual <Plug> mappings are 

    nmap <silent> <Plug>vem_prev_buffer- :call vem_tabline#tabline.select_buffer('left')<CR>
    nmap <silent> <Plug>vem_next_buffer- :call vem_tabline#tabline.select_buffer('right')<CR>
    nmap <silent> <Plug>vem_move_buffer_left- :call vem_tabline#tabline.move_buffer('left')<CR>
    nmap <silent> <Plug>vem_move_buffer_right- :call vem_tabline#tabline.move_buffer('right')<CR>

so the mappings in the documentation don't work 😅

**Comment by pacha** [comment]
Damn, you're right! Fixed. Thanks for reporting :)
