### ISSUE TITLE
VemTablineLocationSelected is not implemented

### ISSUE THREAD

**Issue by baodrate** [pacha/vem-tabline#5]
`VemTablineLocationSelected` doesn't seem to be implemented, although it's in the documentation.

also, a `VemTablineLocationShown` would be useful as well. I'll try to do this if you don't already have it uncommitted somewhere, although I haven't really looked into the code yet.

**Comment by pacha** [comment]
Oh, you're right. That is something I initially wanted to support and I somehow ended up not adding. I didn't think of `VemTablineLocationShown`, but it makes total sense. I just made the changes in: a72065d68f8c841f163f15f2d1e6393b34dcaf1e

It's already in master. I made some initial testing but it would be great if you could tell me if it works for you.

**Comment by baodrate** [comment]
awesome, I'll check it out soon, thanks!
