### ISSUE TITLE
Using only to close split causes error

### ISSUE THREAD

**Issue by ranebrown** [pacha/vem-tabline#7]
When viewing two splits and then collapsing to a single split using `:only` results in the following error when trying to cycle to the next buffer:
```vim
Error detected while processing function 7[5]..8:
line   10:
E16: Invalid range: 2wincmd w
```

**Comment by pacha** [comment]
True thing. Making a window the only one doesn't seem to trigger any of the tabline autocommands... I added a fix in master and now no error should be raised. However, I'm not super happy with the solution. There's no way to detect a change of window layout with autocommands and then there will be a small delay from the moment you execute `:only` to when the tabline reflects the new status. I'll keep an eye on this to see if it can be somehow improved in the future. The delay doesn't affect if you cycle to the next buffer, in that moment the tabline is updated anyways.

Tell me if it works for you and thanks for reporting!

**Comment by ranebrown** [comment]
That seems to work. Thanks!
