### ISSUE TITLE
Default buffer mapping like airline

### ISSUE THREAD

**Issue by Futurile** [pacha/vem-tabline#8]
My feature request is to add default mapping capability for buffers in a similar way to Airline.

The context is that I use airline's tabline to display [all buffers](https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L829). I looked at vem-tabline because airline doesn't have the ability to [reorder buffers](https://github.com/pacha/vem-tabline/blob/9ad67ada6d5af26bc0107fa6b35b925855fe801a/doc/tabline.txt#L61) in the tabline. This would be really useful when I have a large number of buffers open but want to bring 3-5 together to edit them. 

Vim-airline has one significant convenience. It creates an internal list of the buffers which can be displayed on the tabline: so you see [N][buffer name]. It sets up Mappings for them (https://github.com/vim-airline/vim-airline/blob/ea7f5d53135db890088666bfb6627e7c6b7388e1/doc/airline.txt#L918). As buffer numbers are fixed, the numbers it displays is an "internal number" and it maps this to the actual buffer number. The effect is that you can see that "4" on the tabline is a particular buffer and then use the mapping (<leader>1 ... 9/0) to immediately jump to that buffer.

Buftaline may have an [alternative](To switch buffers by their ordinal number (https://github.com/ap/vim-buftabline/blob/14d208b1fa5f4308383e3ce429d57c84423029f9/doc/buftabline.txt#L77) implementation.

This is more efficient than anything else I know of when you have long running sessions with a large number of buffers.

**Comment by pacha** [comment]
Hi @Futurile, that's interesting. Do you know what Airline/Buftabline do when there are more buffers than the ones that fit horizontally in the tabline?
In vem-tabline, the names of the buffers at the ends of the available horizontal space can be displayed just partially. For your suggestion to work I guess that only buffers whose complete name is shown should display a number...

**Comment by Futurile** [comment]
- Airline: displays the maximum number of buffers that fit.  It *does* indicate that there are more buffers unseen: it shows '...' on either end.
- Airline: only puts visual numbers next to the first 9 buffer names, as you can see in this screenshot
![Screenshot from 2019-05-06 21-12-03](https://user-images.githubusercontent.com/5851227/57256836-a4231280-704f-11e9-8ec6-beb8cf0b7d24.png)
- Airline: beyond the first 9 buffers no number is shown.

- Buftaline is new to me, but it seems to show a '>' on the right if there are higher numbered buffers that aren't shown, or '<' on the right if there are lower number buffers not being show.
![Screenshot_2019-05-06_22-47-53](https://user-images.githubusercontent.com/5851227/57257410-3841a980-7051-11e9-8e5b-23d71b36e0c0.png)
- It shows a visual number next to the buffer for as many buffers as you have. As you move upwards it shows you the section of buffers: e.g. you move to buffer 9, it shows you now 4<-->12.
- I can only get the mapping function to work for the first 10 buffers. I can't get get it to accept say 'aa' or F5 for buffer 'ordinal' 12th buffer.
 
- For my suggestion I'm really asking for the 'ordinal' buffer on the screen, not the actual buffer number: this is what buftaline calls it. 
- If the buffer isn't being displayed then it's fine not to show the number.
- Both plugins seem to limit the mapping to 10 'ordinal' buffers: maybe this is to stop something like <leader>12 being slow as it waits to see if you hit something after the first number.
- The limitation of just the first 10 buffers being addressable seems fine as long as I we can move the buffers. So something like this:
``` 
[1. foo.txt] [2 bar.txt] [3. baz.txt] [4. newbuffer.txt]

(I hit <leader>1 to get foo.txt, or <leader>4 to get 'newbuffer.txt')

Then I can move 'newbuffer.txt' to be next to foo.txt so it's easy to work on:

[1. foot.txt] [2. newbuffer.txt] [3. bar.txt] [4. baz.txt]

(now I hit <leader>1 to get foo.txt, but when I hit <leader>2 I get 'newbuffer'.txt)
```

**Comment by pacha** [comment]
Thanks for the detailed explanation @Futurile. I agree that that's something that can be pretty useful. I'll check now how easy it is to add it to the code.

**Comment by pacha** [comment]
@Futurile, the feature you requested is already implemented in master. Take a look at the `vem-tabline-selecting-buffers` in the [help file](https://raw.githubusercontent.com/pacha/vem-tabline/master/doc/tabline.txt) to see how to enable it!
